import logging
import re
from pathlib import Path

from .model import Zone

HEADER = "; Generated by daenes, do not edit: it is rewritten on every change."

# The SOA timers, in seconds. They govern secondary servers, which daenes does
# not expect to be feeding: the primary reads the file it is given here.
SOA_REFRESH = 3600
SOA_RETRY = 600
SOA_EXPIRE = 604800
# The last field is how long a name that does not exist stays denied (RFC 2308).
SOA_NEGATIVE_TTL = 600

# The serial out of a zone file daenes wrote, whichever version wrote it. Up to
# daenes 0.2 the TTL was spelled out on every line, this one included.
SOA_SERIAL = re.compile(
    r"^@\s+(?:\d+\s+)?IN\s+SOA\s+\S+\s+\S+\s+(?P<serial>\d+)\b",
    re.MULTILINE,
)


def render(zone: Zone) -> str:
    """Write a zone out as a master file, per RFC 1035 section 5.

    Names are left relative to $ORIGIN and TTLs left to $TTL, so what a reader
    has to check is the records themselves.
    """
    lines = [
        HEADER,
        f"$ORIGIN {zone.origin}.",
        f"$TTL {zone.ttl}",
        f"@ IN SOA {zone.nameserver} {zone.hostmaster} {zone.serial}"
        f" {SOA_REFRESH} {SOA_RETRY} {SOA_EXPIRE} {SOA_NEGATIVE_TTL}",
        f"@ IN NS {zone.nameserver}",
    ]
    lines.extend(
        f"{record.name} IN {'A' if address.version == 4 else 'AAAA'} {address}"
        for record in zone.addresses
        for address in record.addresses
    )
    lines.extend(f"{alias.name} IN CNAME {alias.target}" for alias in zone.aliases)
    return "\n".join(lines) + "\n"


class FileSystemZoneStore:
    """The zone files on disk, one per origin, in one directory."""

    def __init__(self, directory: Path) -> None:
        self._directory = directory

    def _get_path(self, origin: str) -> Path:
        # An origin is a validated domain name, so it holds no path separator
        # and cannot name a file outside the directory.
        return self._directory / f"{origin}.zone"

    def get_serial(self, origin: str) -> int | None:
        """The serial of the zone on disk, or None when there is none to read."""
        path = self._get_path(origin)
        try:
            text = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            logging.debug("No zone file at %s yet", path)
            return None
        except OSError as error:
            logging.warning("Could not read %s", path, exc_info=error)
            return None
        if (match := SOA_SERIAL.search(text)) is None:
            logging.warning("Found no SOA serial in %s, starting a new count", path)
            return None
        return int(match["serial"])

    def save(self, zone: Zone) -> None:
        """Write a zone out, in one step as far as any reader is concerned."""
        path = self._get_path(zone.origin)
        # Written beside the zone and moved onto it, so a DNS server reloading
        # the file never reads half of one.
        temporary = path.with_name(f"{path.name}.tmp")
        temporary.write_text(render(zone), encoding="utf-8")
        temporary.replace(path)
        logging.debug("Wrote %s", path)
