"""Unit tests for daenes.main.zone_files."""

from ipaddress import ip_address
from pathlib import Path

import pytest

from daenes.main.model import AddressRecord, Zone
from daenes.main.zone_files import FileSystemZoneStore, render

from .conftest import ORIGIN, TTL

# What a zone file daenes wrote looked like up to version 0.2, where the TTL
# was spelled out on every line rather than left to a $TTL directive.
LEGACY_ZONE = """$ORIGIN services.internal.
@ 60 IN SOA ns admin 27 3600 600 604800 600
@ 60 IN NS ns
web 60 IN A 172.20.0.2
"""


def make_zone(
    origin: str = ORIGIN,
    serial: int = 1,
    addresses: tuple[AddressRecord, ...] = (),
) -> Zone:
    return Zone(
        origin=origin,
        serial=serial,
        ttl=TTL,
        nameserver="ns",
        hostmaster="admin",
        addresses=addresses,
    )


def make_store(directory: Path) -> FileSystemZoneStore:
    return FileSystemZoneStore(directory=directory)


def test_a_zone_is_written_as_a_master_file():
    """RFC 1035 section 5.1, with the whole file laid out for a reader."""
    zone = make_zone(
        serial=7,
        addresses=(
            AddressRecord(name="ns", addresses=(ip_address("10.0.0.53"),)),
            AddressRecord(
                name="web",
                addresses=(ip_address("172.20.0.2"), ip_address("fd00::2")),
            ),
            AddressRecord(name="www", addresses=(ip_address("172.20.0.2"),)),
        ),
    )

    assert render(zone) == (
        "; Generated by daenes, do not edit: it is rewritten on every change.\n"
        "$ORIGIN services.internal.\n"
        "$TTL 60\n"
        "@ IN SOA ns admin 7 3600 600 604800 600\n"
        "@ IN NS ns\n"
        "ns IN A 10.0.0.53\n"
        "web IN A 172.20.0.2\n"
        "web IN AAAA fd00::2\n"
        "www IN A 172.20.0.2\n"
    )


def test_a_zone_with_nothing_in_it_still_says_who_serves_it():
    """A network everything left is a zone that answers, not a missing file."""
    assert render(make_zone()).endswith("@ IN SOA ns admin 1 3600 600 604800 600\n@ IN NS ns\n")


def test_a_saved_zone_is_the_rendered_zone(tmp_path):
    zone = make_zone(addresses=(AddressRecord("web", (ip_address("172.20.0.2"),)),))

    make_store(tmp_path).save(zone)

    assert (tmp_path / f"{ORIGIN}.zone").read_text(encoding="utf-8") == render(zone)


def test_saving_a_zone_leaves_nothing_behind(tmp_path):
    """The file is written aside and moved, never read half written."""
    make_store(tmp_path).save(make_zone())

    assert [path.name for path in tmp_path.iterdir()] == [f"{ORIGIN}.zone"]


def test_saving_a_zone_again_replaces_it(tmp_path):
    store = make_store(tmp_path)

    store.save(make_zone(serial=1))
    store.save(make_zone(serial=2))

    assert store.get_serial(ORIGIN) == 2


def test_the_serial_of_a_zone_is_read_back(tmp_path):
    store = make_store(tmp_path)

    store.save(make_zone(serial=1234))

    assert store.get_serial(ORIGIN) == 1234


def test_the_serial_of_a_zone_of_an_earlier_daenes_is_read_back(tmp_path):
    """Upgrading must not send every secondary server back in time."""
    (tmp_path / f"{ORIGIN}.zone").write_text(LEGACY_ZONE, encoding="utf-8")

    assert make_store(tmp_path).get_serial(ORIGIN) == 27


def test_a_zone_that_was_never_written_has_no_serial(tmp_path):
    assert make_store(tmp_path).get_serial(ORIGIN) is None


def test_a_file_without_a_soa_has_no_serial(tmp_path):
    """Whatever it is, it is not something daenes can carry on from."""
    (tmp_path / f"{ORIGIN}.zone").write_text("not a zone at all\n", encoding="utf-8")

    assert make_store(tmp_path).get_serial(ORIGIN) is None


def test_a_file_that_cannot_be_read_has_no_serial(tmp_path):
    (tmp_path / f"{ORIGIN}.zone").mkdir()

    assert make_store(tmp_path).get_serial(ORIGIN) is None


def test_a_zone_is_written_where_its_origin_says(tmp_path):
    """The origin is a validated domain name, so it stays inside the directory."""
    make_store(tmp_path).save(make_zone(origin="admin.internal"))

    assert (tmp_path / "admin.internal.zone").exists()


def test_saving_into_a_missing_directory_is_not_swallowed(tmp_path):
    """A zones directory that was never mounted is a mistake, and stays loud."""
    with pytest.raises(OSError):
        make_store(tmp_path / "missing").save(make_zone())
